Repository boostcampwm-2021/iOS06-MateRunner, pull requests merged in 2021-11, with the labels that each got.

#9 초기 지도 화면 및 달리기 모드 세팅 화면 UI 및 구조
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningModeSettingViewModel.swift
  MateRunner/MateRunner/Resource/Info.plist
  MateRunner/MateRunner/Util/Extension/UIColor+CustomColor.swift
  MateRunner/MateRunner/Util/Extension/UIView+ShadowEffect.swift
Labels: feature, review

#6 폰트 에셋 추가 & 혼자 달리기 결과 UI & 혼자 달리기 결과 화면 흐름 잡기
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Home/ResultUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningResultViewModel.swift
  MateRunner/MateRunner/Resource/Asset/Font/NotoSans-boldItalic.ttf
  MateRunner/MateRunner/Resource/Info.plist
  MateRunner/MateRunner/Util/Extension/UIFont+CustomFont.swift
Labels: feature, review

#7 달리기 모드 선택 화면, 목표 거리 설정 화면 Clean Architecture 적용
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Home/DistanceSettingUseCase.swift
  MateRunner/MateRunner/Presentation/Common/View/RoundedButton.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/DistanceSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MateRunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/DistanceSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/MateRunningModeSettingViewModel.swift
  MateRunner/MateRunner/Util/PropertyWrapper/BehaviorRelayProperty.swift
Labels: feature, review

#26 운동 시작 전 타이머 화면 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner.xcodeproj/xcshareddata/xcschemes/RunningPreparationViewModelTests.xcscheme
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningPreparationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningPreparationUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningPreparationViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningPreparationViewModel.swift
  MateRunner/Podfile
  MateRunner/Podfile.lock
  MateRunner/Tests/RunningPreparationViewModelTests/MockRunningPreparationUseCase.swift
  MateRunner/Tests/RunningPreparationViewModelTests/RunningPreparationViewModelTests.swift
Labels: feature, review, 여훈

#28 초기 지도화면 표시
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Home/RunningSettingUseCase.swift
  MateRunner/MateRunner/MateRunner.entitlements
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MateRunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningModeSettingViewModel.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewController/RecordViewController.swift
  MateRunner/MateRunner/Resource/Info.plist
Labels: feature, review, 유진

#29 운동 중 화면 - 혼자 달리기 모드 UI 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningInfoView.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningProgressView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/DistanceSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
Labels: feature, review, 정원

#32 RunningResultDataService 구현 & RunningResultDTO 구현 & mode 변경
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Network/DTO/RunningResultDTO.swift
  MateRunner/MateRunner/Data/Network/Service/RunningResultDataService.swift
  MateRunner/MateRunner/Domain/Model/RaceRunningResult.swift
  MateRunner/MateRunner/Domain/Model/RunningResult.swift
  MateRunner/MateRunner/Domain/Model/TeamRunningResult.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MateRunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/MateRunningModeSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningModeSettingViewModel.swift
  MateRunner/MateRunner/Util/Constant/Emoji.swift
  MateRunner/MateRunner/Util/Constant/RunningMode.swift
Labels: bug, feature, 민지

#30 목표거리 설정 유효성 검사
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Home/DistanceSettingUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/CursorDisabledTextField.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/DistanceSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/DistanceSettingViewModel.swift
Labels: feature, 여훈

#40 거리설정 유즈케이스, 뷰모델 테스트 추가
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner.xcodeproj/xcshareddata/xcschemes/MateRunner.xcscheme
  MateRunner/MateRunner.xcodeproj/xcshareddata/xcschemes/RunningPreparationViewModelTests.xcscheme
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultDistanceSettingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/DistanceSettingUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/DistanceSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/DistanceSettingViewModel.swift
  MateRunner/Podfile
  MateRunner/Podfile.lock
  MateRunner/Tests/DistanceSettingTests/DistanceSettingUseCaseTests.swift
  MateRunner/Tests/DistanceSettingTests/DistanceSettingViewModelTests.swift
  MateRunner/Tests/DistanceSettingTests/MockDistanceSettingUseCase.swift
  MateRunner/Tests/RunningPreparationTests/MockRunningPreparationUseCase.swift
  MateRunner/Tests/RunningPreparationTests/RunningPreparationViewModelTests.swift
Labels: review, 여훈

#45 운동 중 화면 현재 위치, 경로 Map에 표시
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MapViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
Labels: feature, review, 정원

#49 지도화면 Back Button 동작 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/HomeScene/Protocol/BackButtonDelegate.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MapViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
Labels: feature, review, 정원

#47 달리기 결과 화면 데이터 포매팅 & 달리기 결과 전송 구현 & 달린 좌표에 따른 지도 표시
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Network/DTO/RunningResultDTO.swift
  MateRunner/MateRunner/Data/Network/DataMapping/RunningResultDTO+Mapping.swift
  MateRunner/MateRunner/Data/Network/Service/RunningResultDataService.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningResultRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/RunningResultRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultResultUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningResultUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/ResultUseCase.swift
  MateRunner/MateRunner/Network/FIreStoreNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/NetworkService.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningResultViewModel.swift
  MateRunner/MateRunner/Util/Extension/Date+Formatter.swift
Labels: feature, 민지

#43 실시간 이동 거리 계산
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Home/CoreMotionManager.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningInfoView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SingleRunningViewModel.swift
  MateRunner/MateRunner/Resource/Info.plist
Labels: feature, review, 유진

#48 현재 위치정보 허용 - 설정창 띄우기
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
Labels: feature, 유진

#46 RxTimeInterval로 타이머 재구성
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningPreparationUseCase.swift
Labels: 여훈, refactor

#53 Conflict 해결, 테스트 정리
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner.xcodeproj/xcshareddata/xcschemes/MateRunner.xcscheme
  MateRunner/MateRunner.xcodeproj/xcshareddata/xcschemes/RunningPreparationViewModelTests.xcscheme
  MateRunner/MateRunner/Domain/UseCase/Home/CoreMotionManager.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultDistanceSettingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/DistanceSettingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningInfoView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/DistanceSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/DistanceSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SingleRunningViewModel.swift
  MateRunner/Podfile
  MateRunner/Podfile.lock
  MateRunner/Tests/DistanceSettingTests/DistanceSettingUseCaseTests.swift
  MateRunner/Tests/DistanceSettingTests/DistanceSettingViewModelTests.swift
  MateRunner/Tests/DistanceSettingTests/MockDistanceSettingUseCase.swift
  MateRunner/Tests/RunningPreparationTests/MockRunningPreparationUseCase.swift
  MateRunner/Tests/RunningPreparationTests/RunningPreparationViewModelTests.swift
  MateRunner/Tests/SingleRunningTests/MockSingleRunningUseCase.swift
  MateRunner/Tests/SingleRunningTests/SingleRunningViewModelTests.swift
Labels: fix

#52 실시간 칼로리 계산
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Home/CoreMotionManager.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SingleRunningViewModel.swift
  MateRunner/MateRunner/Util/Constant/Mets.swift
Labels: feature, review, 유진, refactor

#62 운동 중 화면 (경쟁 모드, 협동 모드) UI 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningCardView.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningInfoView.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningProgressView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RaceRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/TeamRunningViewController.swift
Labels: feature, review, 정원

#63 앱, 탭바 코디네이터 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Application/SceneDelegate.swift
  MateRunner/MateRunner/Domain/UseCase/Home/HomeUseCase.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultAppCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultTabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Protocol/AppCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Protocol/Coordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Protocol/CoordinatorFinishDelegate.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Protocol/TabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/ViewController/TabBarController.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultHomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/HomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  MateRunner/MateRunner/Util/Constant/CoordinatorType.swift
  MateRunner/MateRunner/Util/Constant/TabBarPage.swift
Labels: feature, review, 여훈, refactor

#64 실시간 데이터베이스 관련사항 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Repository/Home/DefaultTeamRunningRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/TeamRunningRepository.swift
  MateRunner/MateRunner/Domain/Model/RunningRealTimeData.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultTeamRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/TeamRunningUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/TeamRunningViewModel.swift
Labels: feature, 민지

#58 실시간 데이터 Subject -> RealTimeData 구조체로 변경
  MateRunner/MateRunner/Domain/Model/RunningData.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SingleRunningViewModel.swift
Labels: review, 유진, refactor

#66 친구 목록 테이블뷰 검색바 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/MateUseCase.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultTabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateHeaderView.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
Labels: feature, review, 유진

#76 [Feat] 경쟁 모드, 협동 모드, 중도 취소에 대한 결과 화면 뷰 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/HomeScene/View/MyResultView.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RaceResultView.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/TeamResultView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/CancelRunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RaceRunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/TeamRunningResultViewController.swift
Labels: feature, review, 정원, refactor

#77 초대장 뷰, 메이트 선택 뷰
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/HomeScene/View/InvitationView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/InvitationViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/InviteMateViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MateRunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateEmptyView.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
  MateRunner/MateRunner/Util/Extension/Double+Formatter.swift
Labels: feature, review, 유진

#78 Home, Setting 코디네이터 구현 및 달리기 세팅 데이터 전달
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultDistanceSettingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningPreparationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningSettingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningPreparationUseCase.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultTabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultHomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/HomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/RunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/SettingCoordinatorDidFinishDelegate.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/DistanceSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MateRunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningPreparationViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/DistanceSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/MateRunningModeSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningModeSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningPreparationViewModel.swift
  MateRunner/MateRunner/Util/Constant/CoordinatorType.swift
Labels: feature, review, 여훈

#89 운동 중 화면 코디네이터 연결 - 혼자달리기 모드
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningPreparationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningPreparationUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultHomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/HomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/RunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningPreparationViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningPreparationViewModel.swift
  MateRunner/MateRunner/Util/Constant/CoordinatorType.swift
Labels: feature, review, 여훈

#91 이모지 모달 화면 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Presentation/Common/ViewController/EmojiViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
  MateRunner/MateRunner/Util/Constant/Emoji.swift
Labels: feature, review, 유진

#94 혼자달리기 결과화면 코디네이터 연결
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/RunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/RunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/MateRunningModeSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SingleRunningViewModel.swift
Labels: feature, 여훈

#95 초대 대기 화면 및 기능 구현 & 모델 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Data/Network/DataMapping/InvitationRequestDTO.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInviteMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultTeamRunningRepository.swift
  MateRunner/MateRunner/Domain/Model/Invitation.swift
  MateRunner/MateRunner/Domain/Model/RunningResult.swift
  MateRunner/MateRunner/Domain/Model/RunningSetting.swift
  MateRunner/MateRunner/Domain/Model/Session.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultInvitationWaitingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultMockInviteMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningSettingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultTeamRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/InvitationWaitingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningSettingUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/RunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/InvitationWaitingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/DistanceSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/InvitationWaitingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/MockInviteMateViewModel.swift
  MateRunner/MateRunner/Util/Constant/User.swift
Labels: 민지, refactor

#99 메이트 선택화면 코디네이터 연결
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MateRunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MateSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/MateSettingViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
Labels: feature, review, 여훈

#101 이모지 모달 뷰 리팩토링 뷰모델 유즈케이스
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultEmojiUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Common/Protocol/EmojiUseCase.swift
  MateRunner/MateRunner/Presentation/Common/ViewController/EmojiViewController.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/EmojiViewModel.swift
  MateRunner/MateRunner/Util/Constant/Emoji.swift
Labels: review, 유진, refactor

#104 LocationService 구현, MapViewController에 LocationService 적용
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Repository/Home/DefaultLocationRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultLocationService.swift
  MateRunner/MateRunner/Data/Repository/Home/LocationService.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/LocationRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultMapUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/MapUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MapViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/MapViewModel.swift
Labels: feature, review, 여훈, refactor

#106 로그인 화면 UI 구현, 버튼 동작 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultAppCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/DefaultLoginCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/DefaultSignUpCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/Protocol/LoginCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/Protocol/SignUpCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewController/LoginViewController.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewController/SignUpViewController.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  MateRunner/MateRunner/Resource/Asset/Font/RacingSansOne.ttf
  MateRunner/MateRunner/Resource/Info.plist
  MateRunner/MateRunner/Util/Constant/CoordinatorType.swift
  MateRunner/MateRunner/Util/Extension/UIFont+CustomFont.swift
Labels: feature, review, 정원

#102 칼로리 버그 해결
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/EmojiViewModel.swift
  MateRunner/MateRunner/Util/Constant/Mets.swift
  MateRunner/MateRunner/Util/Service/CoreMotionService.swift
Labels: bug, review, 유진

#113 혼자 달리기 모드 좌표 저장 로직 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/Model/RunningData.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultMapUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/LocationDidUpdateDelegate.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/MapUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SingleRunningViewModel.swift
Labels: feature, review, 여훈

#118 서비스 의존성 분리, RunningUseCase, ViewModel 리팩토링
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/Model/RunningData.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultMapUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/MapUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SingleRunningViewModel.swift
  MateRunner/MateRunner/Util/Service/DefaultCoreMotionService.swift
  MateRunner/MateRunner/Util/Service/DefaultLocationService.swift
  MateRunner/MateRunner/Util/Service/DefaultRxTimerService.swift
  MateRunner/MateRunner/Util/Service/Protocol/CoreMotionService.swift
  MateRunner/MateRunner/Util/Service/Protocol/LocationService.swift
  MateRunner/MateRunner/Util/Service/Protocol/RxTimerService.swift
Labels: review, 여훈, fix, refactor

#117 회원가입 화면 UI 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/SignUp/DefaultSignUpUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/SignUp/Protocol/SignUpUseCase.swift
  MateRunner/MateRunner/Presentation/Common/View/PickerTextField.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/DefaultSignUpCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewController/SignUpViewController.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewModel/SignUpViewModel.swift
Labels: feature, review, 정원

#115 이모지 컬렉션뷰 DataSource -> rx 및 메이트 화면 코디네이터 연결
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultTabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/ViewController/EmojiViewController.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/EmojiViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MateSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/MateSettingViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/Protocol/MateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
  MateRunner/MateRunner/Util/Constant/CoordinatorType.swift
Labels: feature, review, 유진, refactor

#109 초대 대기 중 타임아웃 구현
  MateRunner/MateRunner/Data/Repository/Home/DefaultInviteMateRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultInvitationWaitingUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultHomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/InvitationWaitingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/InvitationWaitingViewModel.swift
Labels: feature, 민지, refactor

#124 혼자달리기 뷰-데이터 바인딩
  MateRunner/MateRunner/Domain/Model/RunningResult.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultResultUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningResultUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningResultViewModel.swift
Labels: feature, 여훈

#130 홈 화면 CoreLocation Manager를 서비스로 분리
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Repository/Home/DefaultLocationRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/LocationRepository.swift
  MateRunner/MateRunner/Domain/Model/Region.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultHomeUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultMapUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/HomeUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/HomeUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/MapUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultHomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningResultViewModel.swift
  MateRunner/MateRunner/Util/Constant/LocationAuthorizationStatus.swift
  MateRunner/MateRunner/Util/Extension/Point+CLLocationCoordinate2D.swift
  MateRunner/MateRunner/Util/Service/DefaultLocationService.swift
  MateRunner/MateRunner/Util/Service/Protocol/LocationService.swift
Labels: feature, 여훈, refactor

#126 친구 목록관련 UseCase, Service, Repository
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningResultRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/DefaultMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/Protocol/MateRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/MateUseCase.swift
  MateRunner/MateRunner/Network/DefaultFireStoreNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/FireStoreNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/NetworkService.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
Labels: feature, review, 유진

#125 초대장 수락 및 거부 기능 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Application/SceneDelegate.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInvitationRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/InvitationRepository.swift
  MateRunner/MateRunner/Domain/Model/Invitation.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultInvitationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/InvitationUseCase.swift
  MateRunner/MateRunner/Network/DefaultRealtimeDatabaseNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/RealtimeDatabaseNetworkService.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultAppCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Protocol/AppCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/InvitationView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/InvitationViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/InvitationViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateViewModel.swift
Labels: feature, 민지

#136 TabBar가 보이는 버그 해결
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/MateRunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SingleRunningViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
Labels: 정원, fix

#141 [Fix] 사용자 위치정보가 업데이트 되지 않는 버그 수정
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultHomeUseCase.swift
  MateRunner/MateRunner/Util/Service/DefaultLocationService.swift
  MateRunner/MateRunner/Util/Service/Protocol/LocationService.swift
Labels: bug, review, 여훈, fix

#143 초대장 수신자의 화면전환 버그 수정
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultAppCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultTabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Protocol/Coordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultHomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/InvitationViewModel.swift
Labels: feature, 민지, fix

#146 함께 달리기 모드 지도관련 컴포넌트 주입
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
Labels: feature, review, 여훈

#145 결과데이터 파이어베이스에 저장
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningResultRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/RunningResultRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Home/DefaultResultUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningResultUseCase.swift
  MateRunner/MateRunner/Network/DefaultFireStoreNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/FireStoreNetworkService.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningResultViewModel.swift
  MateRunner/MateRunner/Util/Constant/FirebaseCollection.swift
  MateRunner/MateRunner/Util/Error/FirebaseServiceError.swift
Labels: feature, review, 여훈

#147 메이트 검색 관련 VC, VM ,UseCase, Repository, Service 및 코디네이터 추가
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Repository/Mate/DefaultMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/Protocol/MateRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/MateUseCase.swift
  MateRunner/MateRunner/Network/DefaultFireStoreNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/FireStoreNetworkService.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultAddMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/Protocol/AddMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/Protocol/MateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/AddMateTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateHeaderView.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/AddMateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/AddMateViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateViewModel.swift
  MateRunner/MateRunner/Resource/Asset/Assets.xcassets/person-add.imageset/Contents.json
  MateRunner/MateRunner/Resource/Asset/Assets.xcassets/person-add.imageset/person-add.png
  MateRunner/MateRunner/Resource/Asset/Assets.xcassets/person-add.imageset/person-add@2x.png
  MateRunner/MateRunner/Resource/Asset/Assets.xcassets/person-add.imageset/person-add@3x.png
  MateRunner/MateRunner/Util/Constant/CoordinatorType.swift
Labels: feature, review, 유진

#155 기록 화면 View 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultTabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/View/CumulativeRecordView.swift
  MateRunner/MateRunner/Presentation/Common/View/RecordCell.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/DefaultRecordCoordinator.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/Protocol/RecordCoordinator.swift
  MateRunner/MateRunner/Presentation/RecordScene/View/CalendarCell.swift
  MateRunner/MateRunner/Presentation/RecordScene/View/CalendarHeaderView.swift
  MateRunner/MateRunner/Presentation/RecordScene/View/CalendarView.swift
  MateRunner/MateRunner/Presentation/RecordScene/View/WeekdayView.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewController/RecordViewController.swift
  MateRunner/MateRunner/Util/Constant/CoordinatorType.swift
Labels: feature, 정원

#160 메이트 친구 요청 FCM 전송
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Network/DataMapping/MessagingRequestDTO.swift
  MateRunner/MateRunner/Data/Repository/Mate/DefaultMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/Protocol/MateRepository.swift
  MateRunner/MateRunner/Domain/Model/MateRequest.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/MateUseCase.swift
  MateRunner/MateRunner/Network/DefaultRealtimeDatabaseNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/RealtimeDatabaseNetworkService.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultAddMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/AddMateTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/AddMateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/AddMateViewModel.swift
Labels: feature, review, 유진

#164 결과 화면 진입 시 결과 저장 구현
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningResultRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/RunningResultRepository.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningResultViewModel.swift
  MateRunner/MateRunner/Util/Error/FirebaseServiceError.swift
Labels: feature, 여훈, refactor

#169 홈 탭 폴더링 세부 흐름별로 분류
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultInvitationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Common/Protocol/InvitationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/ResultUseCase/DefaultResultUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/RunningUseCase/DefaultMapUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/RunningUseCase/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/SettingUseCase/DefaultDistanceSettingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/SettingUseCase/DefaultInvitationWaitingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/SettingUseCase/DefaultRunningPreparationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/SettingUseCase/DefaultRunningSettingUseCase.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Delegate/CoordinatorFinishDelegate.swift
  MateRunner/MateRunner/Presentation/Common/ViewController/InvitationViewController.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/InvitationViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/Delegate/BackButtonDelegate.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/ResultViewController/CancelRunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/ResultViewController/RaceRunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/ResultViewController/RunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/ResultViewController/TeamRunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/MapViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/RaceRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/RunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/SingleRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/TeamRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/DistanceSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/InvitationWaitingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/MateRunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/MateSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/RunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/RunningPreparationViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/ResultViewModel/RunningResultViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/MapViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/RaceRunningViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/SingleRunningViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/TeamRunningViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SettingViewModel/DistanceSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SettingViewModel/InvitationWaitingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SettingViewModel/MateRunningModeSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SettingViewModel/MateSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SettingViewModel/RunningModeSettingViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SettingViewModel/RunningPreparationViewModel.swift
Labels: 여훈, chore

#171 친구 프로필 뷰 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/Common/View/RecordCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/Protocol/MateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateHeaderView.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateProfileTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateRecordTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/AddMateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateProfileViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateProfileViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateViewModel.swift
Labels: feature, review, 유진

#174 달리기 종료조건 수정, 관련코드 리팩토링
  MateRunner/MateRunner/Domain/Model/RunningResult.swift
  MateRunner/MateRunner/Domain/UseCase/Home/RunningUseCase/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/InvitationView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/ResultViewModel/RunningResultViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/RaceRunningViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/SingleRunningViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/TeamRunningViewModel.swift
  MateRunner/MateRunner/Util/Extension/Double+Formatter.swift
Labels: bug, review, fix, refactor

#176 결과화면 뷰 리팩토링
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/ResultViewController/CancelRunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/ResultViewController/RaceRunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/ResultViewController/RunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/ResultViewController/SingleRunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/ResultViewController/TeamRunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/ResultViewModel/RaceRunningResultViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/ResultViewModel/SingleRunningResultViewModel.swift
Labels: review, 여훈, refactor

#185 거리 설정 시 밑줄이 사라지는 버그 수정
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/DistanceSettingViewController.swift
Labels: bug, review, 여훈, fix

#178 DefaultInviteMateRepository 및 DefaultRunningRepository 리팩토링 & 환경변수 분리 & 초대장 이모티콘 표시 수정
  .gitignore
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Data/Network/DataMapping/InvitationRequestDTO.swift
  MateRunner/MateRunner/Data/Network/DataMapping/MessagingRequestDTO.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInvitationRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInviteMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/InvitationRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/InviteMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/RunningRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultInvitationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Common/Protocol/InvitationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/RunningUseCase/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/SettingUseCase/DefaultInvitationWaitingUseCase.swift
  MateRunner/MateRunner/Network/DefaultRealtimeDatabaseNetworkService.swift
  MateRunner/MateRunner/Network/DefaultURLSessionNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/RealtimeDatabaseNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/URLSessionNetworkService.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/InvitationViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/InvitationView.swift
  MateRunner/MateRunner/Resource/Info.plist
  MateRunner/MateRunner/Util/Constant/Configuration.swift
Labels: bug, 민지, refactor

#182 누적기록 바인딩, 달력 기능 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/Model/CalendarModel.swift
  MateRunner/MateRunner/Domain/UseCase/Record/DefaultRecordUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Record/Protocol/RecordUseCase.swift
  MateRunner/MateRunner/Presentation/Common/View/RecordCell.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/DefaultRecordCoordinator.swift
  MateRunner/MateRunner/Presentation/RecordScene/View/CalendarCell.swift
  MateRunner/MateRunner/Presentation/RecordScene/View/WeekdayView.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewController/RecordViewController.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewModel/RecordViewModel.swift
  MateRunner/MateRunner/Util/Extension/Date+Formatter.swift
  MateRunner/MateRunner/Util/Extension/Double+Formatter.swift
  MateRunner/MateRunner/Util/Extension/Int+Formatter.swift
Labels: feature, 정원

#191 달리기 중도 취소 관련 사항 구현 & isRunning 상태 서버 업로드
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInvitationRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInviteMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/InvitationRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/InviteMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/RunningRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultInvitationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Common/Protocol/InvitationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/RunningUseCase/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/SettingUseCase/DefaultInvitationWaitingUseCase.swift
  MateRunner/MateRunner/Network/DefaultRealtimeDatabaseNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/RealtimeDatabaseNetworkService.swift
  MateRunner/MateRunner/Presentation/Common/ViewController/InvitationViewController.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/InvitationViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/RaceRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/TeamRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/RaceRunningViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/TeamRunningViewModel.swift
Labels: feature, 민지

#189 메이트 프로필, 기록 UseCase, Repository, Service DTO변경
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Network/DataMapping/RunningResultDTO+Mapping.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/UserRepository.swift
  MateRunner/MateRunner/Domain/Model/UserProfile.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultProfileUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/ProfileUseCase.swift
  MateRunner/MateRunner/Network/DefaultFireStoreNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/FireStoreNetworkService.swift
  MateRunner/MateRunner/Presentation/Common/View/RecordCell.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/TeamRunningViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/Protocol/MateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateRecordTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateProfileViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateProfileViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateViewModel.swift
  MateRunner/MateRunner/Util/Extension/Date+Formatter.swift
Labels: feature, review, 유진, refactor

#193 Apple Login 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/UserRepository.swift
  MateRunner/MateRunner/Data/Repository/SignUp/DefaultSignUpRepository.swift
  MateRunner/MateRunner/Data/Repository/SignUp/Protocol/SignUpRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Account/DefaultLoginUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Account/DefaultSignUpUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Account/Protocol/LoginUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Account/Protocol/SignUpUseCase.swift
  MateRunner/MateRunner/MateRunner.entitlements
  MateRunner/MateRunner/Network/DefaultFireStoreNetworkService.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultAppCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/DefaultLoginCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/DefaultSignUpCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/Protocol/LoginCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewController/LoginViewController.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  MateRunner/MateRunner/Storage/DefaultUserDefaultPersistence.swift
  MateRunner/MateRunner/Storage/Protocol/UserDefaultPersistence.swift
  MateRunner/MateRunner/Util/Constant/FirebaseCollection.swift
  MateRunner/Podfile
  MateRunner/Podfile.lock
Labels: feature, 정원, refactor

#196 달리기 시작 및 종료 시 Running state 업데이트 구현 & 초대장 타임아웃 관련 버그 수정 & 혼자 달리기 시 서버에 실시간 데이터 업로드되지 않도록 수정
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/RunningRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/RunningUseCase/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Presentation/Common/ViewController/InvitationViewController.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/InvitationViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/RaceRunningViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/SingleRunningViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/TeamRunningViewModel.swift
Labels: feature, 민지, fix

#200 마이페이지 뷰 구현 & 뷰모델 Input 정의 & 코디네이터 연결
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/Protocol/MyPageUseCase.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultTabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultMyPageCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/Protocol/MyPageCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  MateRunner/MateRunner/Resource/Asset/Assets.xcassets/bell.imageset/Contents.json
  MateRunner/MateRunner/Resource/Asset/Assets.xcassets/bell.imageset/bell.png
  MateRunner/MateRunner/Resource/Asset/Assets.xcassets/bell.imageset/bell@2x.png
  MateRunner/MateRunner/Resource/Asset/Assets.xcassets/bell.imageset/bell@3x.png
  MateRunner/MateRunner/Util/Constant/CoordinatorType.swift
Labels: feature, 민지

#197 메이트 화면 리팩토링 및 메이트 목록 인디케이터 추가
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/MateUseCase.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/AddMateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/AddMateViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateViewModel.swift
Labels: feature, review, 유진, refactor

#201 메이트 요청시 FCM 전송과 함께 DB저장
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Network/DataMapping/NoticeDTO+Mapping.swift
  MateRunner/MateRunner/Data/Network/DataMapping/UserProfileDTO.swift
  MateRunner/MateRunner/Data/Repository/Mate/DefaultMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/Protocol/MateRepository.swift
  MateRunner/MateRunner/Domain/Model/Notice.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/MateUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultAddMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/AddMateTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/AddMateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/AddMateViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateViewModel.swift
  MateRunner/MateRunner/Util/Constant/NoticeMode.swift
Labels: feature, review, 유진

#199 기록 상세화면 구현, 모델 바인딩
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Record/DefaultRecordDetailUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Record/Protocol/RecordDetailUseCase.swift
  MateRunner/MateRunner/Presentation/Common/View/EmojiListView.swift
  MateRunner/MateRunner/Presentation/Common/View/EmojiView.swift
  MateRunner/MateRunner/Presentation/Common/View/RecordCell.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RaceResultView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/TeamRunningViewModel.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/DefaultRecordCoordinator.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/Protocol/RecordCoordinator.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewController/RecordDetailViewController.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewController/RecordViewController.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewModel/RecordDetailViewModel.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewModel/RecordViewModel.swift
  MateRunner/MateRunner/Util/Extension/Double+Formatter.swift
  MateRunner/MateRunner/Util/Extension/Int+Formatter.swift
Labels: feature, 정원

#219 기록화면 서버 데이터 바인딩, 기록 상세화면 연결
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Record/DefaultRecordDetailUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Record/DefaultRecordUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Record/Protocol/RecordDetailUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Record/Protocol/RecordUseCase.swift
  MateRunner/MateRunner/Presentation/Common/View/RecordCell.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/DefaultRecordCoordinator.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/Protocol/RecordCoordinator.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewController/RecordViewController.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewModel/RecordDetailViewModel.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewModel/RecordViewModel.swift
  MateRunner/MateRunner/Util/Extension/Int+Formatter.swift
Labels: feature, 정원

#213 마이페이지 코디네이터 연결 & ViewController, ViewModel, UseCase 생성
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultNotificationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultProfileEditUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/Protocol/NotificationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/Protocol/ProfileEditUseCase.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultLicenseCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultMyPageCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultNotificationCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultProfileEditCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/Protocol/LicenseCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/Protocol/MyPageCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/Protocol/NotificationCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/Protocol/ProfileEditCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/LicenseViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/NotificationViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/ProfileEditViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/NotificationViewModel.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/ProfileEditViewModel.swift
  MateRunner/MateRunner/Util/Constant/CoordinatorType.swift
Labels: feature, 민지

#220 이미지 캐싱 구현 및 프로필 이미지 띄우기
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Network/DataMapping/UserProfileDTO.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningResultRepository.swift
  MateRunner/MateRunner/Network/DefaultFireStoreNetworkService.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateProfileTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateProfileViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateProfileViewModel.swift
  MateRunner/MateRunner/Util/Error/ImageCacheError.swift
  MateRunner/MateRunner/Util/Extension/UIImageView+ImageCache.swift
  MateRunner/MateRunner/Util/Service/DefaultImageCacheService.swift
Labels: feature, review, 유진

#217 RestAPI 요청 레파지토리 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Network/DataMapping/EmojiFirestoreDTO.swift
  MateRunner/MateRunner/Data/Network/DataMapping/MateListFirestoreDTO.swift
  MateRunner/MateRunner/Data/Network/DataMapping/PersonalTotalRecordDTO.swift
  MateRunner/MateRunner/Data/Network/DataMapping/RunningResultFirestoreDTO.swift
  MateRunner/MateRunner/Data/Network/DataMapping/UserDataFirestoreDTO.swift
  MateRunner/MateRunner/Data/Network/DataMapping/UserProfileFirestoreDTO.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/FirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInviteMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningResultRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/DefaultMateRepository.swift
  MateRunner/MateRunner/Domain/Model/FirestoreValues.swift
  MateRunner/MateRunner/Domain/Model/PersonalTotalRecord.swift
  MateRunner/MateRunner/Domain/Model/Point.swift
  MateRunner/MateRunner/Domain/Model/RaceRunningResult.swift
  MateRunner/MateRunner/Domain/Model/RunningResult.swift
  MateRunner/MateRunner/Domain/Model/TeamRunningResult.swift
  MateRunner/MateRunner/Domain/Model/UserData.swift
  MateRunner/MateRunner/Domain/Model/UserProfile.swift
  MateRunner/MateRunner/Domain/UseCase/Home/ResultUseCase/DefaultRunningResultUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/RunningUseCase/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Network/DefaultURLSessionNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/URLSessionNetworkService.swift
  MateRunner/MateRunner/Util/Constant/FirestoreQuery.swift
  MateRunner/MateRunner/Util/Error/FirebaseServiceError.swift
  MateRunner/MateRunner/Util/Extension/Date+Formatter.swift
  MateRunner/MateRunner/Util/Factory/RunningResultFactory.swift
  MateRunner/MateRunner/Util/TemporaryResultDTO.swift
Labels: feature, review, 여훈

#223 오픈소스 라이센스 화면 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/LicenseViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  MateRunner/MateRunner/Resource/license.txt
Labels: feature, 정원

#225 알림 확인 기능 및 친구 수락 기능 구현
  MateRunner/MateRunner/Data/Network/DataMapping/NoticeDTO+Mapping.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/DefaultMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/Protocol/MateRepository.swift
  MateRunner/MateRunner/Domain/Model/FirestoreValues.swift
  MateRunner/MateRunner/Domain/Model/Notice.swift
  MateRunner/MateRunner/Domain/UseCase/Home/SettingUseCase/DefaultInvitationWaitingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultNotificationUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/Protocol/NotificationUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultAddMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultNotificationCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/View/NotificationTableViewCell.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/NotificationViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/NotificationViewModel.swift
Labels: feature, 민지

#227 프로필 정보(키, 몸무게) 편집 기능 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultProfileEditUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/Protocol/MyPageUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/Protocol/ProfileEditUseCase.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultMyPageCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultProfileEditCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/Protocol/MyPageCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/Protocol/ProfileEditCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/View/ImageEditButton.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/LicenseViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/ProfileEditViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/ProfileEditViewModel.swift
  MateRunner/MateRunner/Util/Constant/FilePath.swift
Labels: feature, 정원

#230 메이트관련 Rest API 전환 및 이모지, 화면전환
  MateRunner/MateRunner/Data/Network/DataMapping/RunningResultFirestoreDTO.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/FirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/DefaultMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/Protocol/MateRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultEmojiUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultProfileUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/ProfileUseCase.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/EmojiViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/RunningCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultAddMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/Protocol/MateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateRecordTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateProfileViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateProfileViewModel.swift
Labels: feature, review, 유진

#231 누적기록 업데이트, URLSession서비스 개선
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/FirestoreRepository.swift
  MateRunner/MateRunner/Domain/Model/PersonalTotalRecord.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningResultUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/ResultUseCase/DefaultRunningResultUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultProfileUseCase.swift
  MateRunner/MateRunner/Network/DefaultURLSessionNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/URLSessionNetworkService.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/ResultViewModel/RaceRunningResultViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/ResultViewModel/TeamRunningResultViewModel.swift
Labels: feature, 여훈, refactor

#236 프로필 사진 저장, 불러오기 Rest 레파지토리 구현
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/FirestoreRepository.swift
  MateRunner/MateRunner/Network/DefaultURLSessionNetworkService.swift
Labels: feature, review, 여훈

#249 탭바가 사라지지 않는 버그 해결
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultLicenseCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultProfileEditCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/LicenseViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/ProfileEditViewController.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/DefaultRecordCoordinator.swift
Labels: bug, 정원, fix

#250 결과 표시 버그 수정 & 다크 모드 대응 & 알림 설정 버튼 삭제 & 콜렉션뷰 배경색 표시 문제 해결
  MateRunner/MateRunner/Domain/UseCase/Home/RunningUseCase/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Presentation/Common/ViewController/EmojiViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/ResultViewController/RunningResultViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/RunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/MateRunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewController/RecordViewController.swift
  MateRunner/MateRunner/Util/Extension/Double+Formatter.swift
Labels: bug, 민지, fix

#251 [메이트 화면] 이모지 Rest API 전송, FCM 전송
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInviteMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/DefaultMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Mate/Protocol/MateRepository.swift
  MateRunner/MateRunner/Domain/Model/ComplimentEmoji.swift
  MateRunner/MateRunner/Domain/Model/RunningResult.swift
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultEmojiUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Common/Protocol/EmojiUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultProfileUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/ProfileUseCase.swift
  MateRunner/MateRunner/Network/DefaultURLSessionNetworkService.swift
  MateRunner/MateRunner/Presentation/Common/ViewController/EmojiViewController.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/EmojiViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/Protocol/MateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateRecordTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateProfileViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateProfileViewModel.swift
Labels: feature, review, 유진

#253 프로필 정보 편집 기능 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultProfileEditUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/Protocol/ProfileEditUseCase.swift
  MateRunner/MateRunner/Presentation/Common/View/MateRunnerActivityIndicatorView.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/ProfileEditViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/ProfileEditViewModel.swift
Labels: feature, 정원, refactor

#254 메이트 화면 관련 버그 fix 및 refresh 관련 추가
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultEmojiUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Common/Protocol/EmojiUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultProfileUseCase.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/EmojiViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateRecordTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/AddMateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateProfileViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateProfileViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateViewModel.swift
Labels: bug, review, 유진, refactor

#256 달리기 초대장, 메이트 요청 푸시알림을 통해 알림센터, 달리기모드 진입, 모든 화면에서 초대장 팝업 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Application/SceneDelegate.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInviteMateRepository.swift
  MateRunner/MateRunner/Domain/Model/Invitation.swift
  MateRunner/MateRunner/Domain/Model/MateRequest.swift
  MateRunner/MateRunner/Domain/UseCase/Home/SettingUseCase/DefaultInvitationWaitingUseCase.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultAppCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultTabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Protocol/AppCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Protocol/Coordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Protocol/InvitationReceivable.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/Protocol/TabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/ViewController/InvitationViewController.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/InvitationViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultHomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/Protocol/HomeCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/InvitationView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/DefaultRecordCoordinator.swift
  MateRunner/MateRunner/Resource/Info.plist
  MateRunner/MateRunner/Util/Constant/NoticeMode.swift
  MateRunner/MateRunner/Util/Constant/NotificationCenterKey.swift
Labels: feature, 여훈, refactor

#258 이모지 삭제 추가 및 Rest API 연결
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultEmojiUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Common/Protocol/EmojiUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultProfileUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/MateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/ProfileUseCase.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/EmojiViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateRecordTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateProfileViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/AddMateViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateProfileViewModel.swift
Labels: feature, review, 유진

#260 REST로 특정 달에 대한 기록 받기
  MateRunner/MateRunner/Domain/UseCase/Record/DefaultRecordUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Record/Protocol/RecordUseCase.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/DefaultRecordCoordinator.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewController/RecordViewController.swift
  MateRunner/MateRunner/Presentation/RecordScene/ViewModel/RecordViewModel.swift
Labels: feature, review, 정원, refactor

#264 emoji를 받아올 수 있도록 수정
  MateRunner/MateRunner/Domain/UseCase/Record/DefaultRecordUseCase.swift
Labels: review, 정원, refactor

#265 메이트,이모지 화면 관련 고정된 닉네임 수정
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultEmojiUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Common/Protocol/EmojiUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultMateUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultProfileUseCase.swift
  MateRunner/MateRunner/Presentation/Common/ViewModel/EmojiViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateRecordTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateProfileViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateProfileViewModel.swift
Labels: 유진, refactor

#266 이미지 캐싱 수정, 프로필 사진 변경 적용
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultProfileEditUseCase.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  MateRunner/MateRunner/Util/Error/ImageCacheError.swift
  MateRunner/MateRunner/Util/Extension/UIImageView+ImageCache.swift
  MateRunner/MateRunner/Util/Service/DefaultImageCacheService.swift
Labels: feature, review, 여훈, fix

#268 결과 쿼리 적용시 오프셋이 주어졌을 때도 디코딩이 되도록 수정
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Domain/Model/FirestoreValues.swift
Labels: review, 여훈, fix

#267 회원가입 및 로그인 시 fcm token 서버에 업로드 구현
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/UserRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Account/DefaultLoginUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Account/DefaultSignUpUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Account/Protocol/LoginUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Account/Protocol/SignUpUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/DefaultLoginCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/DefaultSignUpCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewModel/SignUpViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultAddMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultMyPageCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultNotificationCoordinator.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/DefaultRecordCoordinator.swift
  MateRunner/MateRunner/Util/Constant/UserDefaultKey.swift
Labels: feature, 민지

#269 경쟁 모드에서 프로필 이미지 표시 & 몸무게로 칼로리 계산 & 알림 정렬 & 처리된 초대장이 계속 팝업되는 버그 수정
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/RunningUseCase/DefaultRunningUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningCardView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/RaceRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/RaceRunningViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/SingleRunningViewModel.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/RunningViewModel/TeamRunningViewModel.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/NotificationViewModel.swift
Labels: feature, 민지

#272 이모지 알림 표시
  MateRunner/MateRunner/Data/Network/DataMapping/NoticeDTO+Mapping.swift
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultEmojiUseCase.swift
  MateRunner/MateRunner/Presentation/MyPageScene/View/NotificationTableViewCell.swift
  MateRunner/MateRunner/Util/Constant/NoticeMode.swift
Labels: feature, 민지

#276 메이트 화면 관련 버그 수정 및 emptyLabel 추가
  MateRunner/MateRunner/Presentation/MateScene/View/AddMateTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateProfileViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateProfileViewModel.swift
Labels: bug, review, 유진, fix

#278 달리기 중인 친구 선택 시 alert 표시
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Domain/UseCase/Home/Protocol/RunningSettingUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Home/SettingUseCase/DefaultRunningSettingUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/MateSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SettingViewModel/MateSettingViewModel.swift
Labels: feature, 민지

#281 메이트 프로필 기록 리스트 인피니티 스크롤 페이징 적용
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/UseCase/Mate/DefaultProfileUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Mate/Protocol/ProfileUseCase.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewController/MateProfileViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ViewModel/MateProfileViewModel.swift
  MateRunner/MateRunner/Util/Extension/UIScrollView+ObserveScroll.swift
Labels: feature, review, 유진

#282 캐싱 정책 변경 및 etag를 사용한 조건부 get 구현
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Domain/Model/CacheableImage.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultProfileEditUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningCardView.swift
  MateRunner/MateRunner/Presentation/MateScene/View/AddMateTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateProfileTableViewCell.swift
  MateRunner/MateRunner/Presentation/MateScene/View/MateTableViewCell.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/ProfileEditViewController.swift
  MateRunner/MateRunner/Util/Error/ImageCacheError.swift
  MateRunner/MateRunner/Util/Extension/UIImageView+ImageCache.swift
  MateRunner/MateRunner/Util/Service/DefaultImageCacheService.swift
Labels: 여훈, refactor

#287 탭바 문제 해결
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/HomeViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/RunningModeSettingViewController.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultNotificationCoordinator.swift
Labels: bug, 정원, fix

#288 알람 목록 없을 때 엠티뷰 표시 버그 수정
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultNotificationUseCase.swift
Labels: bug, 민지, fix

#296 Picker관련 코드 개선
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/UserRepository.swift
  MateRunner/MateRunner/Domain/UseCase/Account/DefaultSignUpUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Account/Protocol/SignUpUseCase.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewController/SignUpViewController.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewModel/SignUpViewModel.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/ProfileEditViewModel.swift
  MateRunner/MateRunner/Util/Constant/Height.swift
  MateRunner/MateRunner/Util/Constant/Weight.swift
Labels: 정원, refactor

#319 로그아웃 기능 구현
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/UserRepository.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/Protocol/MyPageUseCase.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultAppCoordinator.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultTabBarCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultMyPageCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
Labels: feature, review, 정원

#339 [리팩토링] REST API 전환
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/FirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/UserRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningResultRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/Protocol/RunningResultRepository.swift
  MateRunner/MateRunner/Domain/Model/FirestoreValues.swift
  MateRunner/MateRunner/Domain/UseCase/Account/DefaultLoginUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Account/DefaultSignUpUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/Account/Protocol/SignUpUseCase.swift
  MateRunner/MateRunner/Network/DefaultFireStoreNetworkService.swift
  MateRunner/MateRunner/Network/Protocol/FireStoreNetworkService.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningCoordinator.swift
  MateRunner/MateRunner/Presentation/HomeScene/Coordinator/DefaultRunningSettingCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/DefaultLoginCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/Coordinator/DefaultSignUpCoordinator.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewModel/SignUpViewModel.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultAddMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateCoordinator.swift
  MateRunner/MateRunner/Presentation/MateScene/ Cooditnator/DefaultMateProfileCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultMyPageCoordinator.swift
  MateRunner/MateRunner/Presentation/MyPageScene/Coordinator/DefaultNotificationCoordinator.swift
  MateRunner/MateRunner/Presentation/RecordScene/Coordinator/DefaultRecordCoordinator.swift
Labels: review, 정원, refactor

#342 [마이페이지 화면] 회원탈퇴 기능 구현
  MateRunner/MateRunner/Data/Repository/Common/DefaultFirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/FirestoreRepository.swift
  MateRunner/MateRunner/Data/Repository/Common/Protocol/UserRepository.swift
  MateRunner/MateRunner/Domain/Model/FirestoreValues.swift
  MateRunner/MateRunner/Domain/UseCase/Account/DefaultSignUpUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/DefaultMyPageUseCase.swift
  MateRunner/MateRunner/Domain/UseCase/MyPage/Protocol/MyPageUseCase.swift
  MateRunner/MateRunner/Presentation/LoginScene/ViewModel/SignUpViewModel.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  MateRunner/MateRunner/Util/Constant/FirestoreQuery.swift
Labels: feature, review, 정원

#344 RealtimeDatabaseKey & UserDefaultKey 리팩토링
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner/Application/AppDelegate.swift
  MateRunner/MateRunner/Application/SceneDelegate.swift
  MateRunner/MateRunner/Data/Repository/Common/DefaultUserRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInvitationRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultInviteMateRepository.swift
  MateRunner/MateRunner/Data/Repository/Home/DefaultRunningRepository.swift
  MateRunner/MateRunner/Network/DefaultRealtimeDatabaseNetworkService.swift
  MateRunner/MateRunner/Presentation/Common/Coordinator/DefaultAppCoordinator.swift
  MateRunner/MateRunner/Util/Constant/RealtimeDatabaseKey.swift
  MateRunner/MateRunner/Util/Constant/UserDefaultKey.swift
Labels: 민지, refactor

#348 MockFirestoreRepository, MockUserRepository 추가
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunnerViewModelTests/Common/Mock/MockFirestoreRepository.swift
  MateRunner/MateRunnerViewModelTests/Common/Mock/MockUserRepository.swift
Labels: feature, review, 유진

#345 Invitation UseCase 테스트 작성
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner.xcodeproj/xcshareddata/xcschemes/MateRunner.xcscheme
  MateRunner/MateRunnerUseCaseTests/HomeScene/InvitationUseCaseTests.swift
  MateRunner/MateRunnerUseCaseTests/HomeScene/MockInvitationRepository.swift
Labels: 민지, test

#355 기록없는 달 기록 개수, 이모지 개수 표시 안되는 버그 해결
  MateRunner/MateRunner/Domain/UseCase/Record/DefaultRecordUseCase.swift
  MateRunner/MateRunner/Presentation/Common/View/RecordCell.swift
Labels: review, 정원, fix

#357 초대장, 달리기 화면 다크모드 대응 & 알림 목록에서 닉네임이 길어졌을 때 표시 수정
  MateRunner/MateRunner/Presentation/HomeScene/View/InvitationView.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningCardView.swift
  MateRunner/MateRunner/Presentation/HomeScene/View/RunningInfoView.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/RunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/RunningViewController/TeamRunningViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/RunningPreparationViewController.swift
  MateRunner/MateRunner/Presentation/MyPageScene/View/NotificationTableViewCell.swift
Labels: 민지, fix

#358 상대방 기록에서도 나의 이름이 표시되는 문제 해결
  MateRunner/MateRunner/Presentation/RecordScene/ViewModel/RecordDetailViewModel.swift
Labels: review, 정원, fix

#356 DistanceSetting 뷰모델, 유즈케이스 테스트, 테스트를 이용한 코드개선
  MateRunner/MateRunner.xcodeproj/project.pbxproj
  MateRunner/MateRunner.xcodeproj/xcshareddata/xcschemes/MateRunner.xcscheme
  MateRunner/MateRunner/Domain/UseCase/Common/DefaultInvitationUseCase.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewController/SettingViewController/DistanceSettingViewController.swift
  MateRunner/MateRunner/Presentation/HomeScene/ViewModel/SettingViewModel/DistanceSettingViewModel.swift
  MateRunner/MateRunnerUseCaseTests/HomeScene/DistanceSettingUseCaseTests.swift
  MateRunner/MateRunnerViewModelTests/HomeScene/DistanceSettingViewModelTests.swift
  MateRunner/MateRunnerViewModelTests/HomeScene/Mock/MockDistanceSettingUseCase.swift
  MateRunner/MateRunnerViewModelTests/HomeScene/Mock/MockRunningSettingUseCase.swift
Labels: review, 여훈, test
